<div id="fb-root"></div>
<script>
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/de_DE/sdk.js#xfbml=1&version=v2.5&appId=<?php echo $block->getAppId() ?>";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

<script>

    var checkFbLikedIntervalId;

    function checkFbLikedRequest($)
    {
        $.getJSON( '<?php echo $block->getControllerUrl() ?>', function( data ) {
            if(data.result == true) {
                $('.fb-like-wrapper').hide();
                $('.box-tocart').show();
                clearInterval(checkFbLikedIntervalId);
            } else {
                $('.box-tocart').hide();
                $('.fb-like-wrapper').show();
            }
        });
    }

    function checkFbLikedInterval($)
    {
        checkFbLikedRequest($);
        checkFbLikedIntervalId = setInterval(function() {
            checkFbLikedRequest($);
        }, 3000);
    }

    require(['jquery'], function($){
        $(document).ready(function() {
            $('.fb-like-wrapper').hide();
            $('.box-tocart').hide();
            checkFbLikedInterval($); // check on intervall
        });
    });

</script>

<div class="fb-like-wrapper">
    <div><span><?php echo __('Like our facebook page to get this article!') ?></span></div>
    <div class="fb-like" data-href="<?php echo $block->getPageUrl(); ?>" data-layout="standard" data-action="like" data-show-faces="true" data-share="false"></div>
</div>
